fix: ignore duplicate OFFSET/BPMS in #NOTEDATA blocks in .ssc-files
This previously caused panic issues with some .ssc files:
thread 'main' panicked at src/patterns.rs:220:23:
range start index 2 out of range for slice of length 0
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_start_index_len_fail::do_panic::runtime
   3: core::slice::index::slice_start_index_len_fail
   4: rssp::patterns::count_anchors
   5: rssp::main